# .github/workflows/caller.yml
name: Caller Workflow

on:
  push:
    branches:
      - main

jobs:
  call-external:
    uses: TESTORGXs3rdz0/PRIVATE_REPO/.github/workflows/secretwf.yml@main
    with:
      message: 'hello";echo "test'
