name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Echo input
        run: echo "Hello ${{ inputs.username }}"
